#!/bin/bash

# docker run -t --rm -v $(pwd):/src:delegated --entrypoint "/bin/bash" kapicorp/kapitan:v0.32.0-rc.0 "generate_kapitan_refs.sh"

time (kapitan refs --write plain:test_secret -f secret.txt)
time (kapitan refs --write plain:test_secret -f secret.txt)
time (kapitan refs --write plain:test_secret -f secret.txt)
time (kapitan refs --write plain:test_secret -f secret.txt)
time (kapitan refs --write plain:test_secret -f secret.txt)
echo "here1"
time (kapitan refs --write plain:test_secret -f secret.txt)
time (kapitan refs --write plain:test_secret -f secret.txt)
time (kapitan refs --write plain:test_secret -f secret.txt)
time (kapitan refs --write plain:test_secret -f secret.txt)
time (kapitan refs --write plain:test_secret -f secret.txt)
echo "here2"
time (kapitan refs --write plain:test_secret -f secret.txt)
time (kapitan refs --write plain:test_secret -f secret.txt)
time (kapitan refs --write plain:test_secret -f secret.txt)
time (kapitan refs --write plain:test_secret -f secret.txt)
time (kapitan refs --write plain:test_secret -f secret.txt)
echo "here3"
time (kapitan refs --write plain:test_secret -f secret.txt)
time (kapitan refs --write plain:test_secret -f secret.txt)
time (kapitan refs --write plain:test_secret -f secret.txt)
time (kapitan refs --write plain:test_secret -f secret.txt)
time (kapitan refs --write plain:test_secret -f secret.txt)
time (kapitan refs --write plain:test_secret -f secret.txt)
time (kapitan refs --write plain:test_secret -f secret.txt)
time (kapitan refs --write plain:test_secret -f secret.txt)
time (kapitan refs --write plain:test_secret -f secret.txt)
time (kapitan refs --write plain:test_secret -f secret.txt)
time (kapitan refs --write plain:test_secret -f secret.txt)
time (kapitan refs --write plain:test_secret -f secret.txt)
time (kapitan refs --write plain:test_secret -f secret.txt)
time (kapitan refs --write plain:test_secret -f secret.txt)
time (kapitan refs --write plain:test_secret -f secret.txt)
time (kapitan refs --write plain:test_secret -f secret.txt)
time (kapitan refs --write plain:test_secret -f secret.txt)
time (kapitan refs --write plain:test_secret -f secret.txt)
time (kapitan refs --write plain:test_secret -f secret.txt)
time (kapitan refs --write plain:test_secret -f secret.txt)
